from app.utils.postman_engine import PostmanScriptEngine

def run_api_logic(payload_from_postman, current_env):
    # 1. Extract the request body from the payload
    # This is the "jsondata" the script needs
    req_body = payload_from_postman.get("request", {}).get("body", {})

    # 2. Extract the script lines
    # Safe navigation through your JSON structure
    events = payload_from_postman.get("event", [])
    script_lines = []
    for event in events:
        if event.get("listen") == "prerequest":
            script_lines = event.get("script", {}).get("exec", [])

    # 3. CALL THE ENGINE (The separate branch)
    if script_lines:
        current_env = PostmanScriptEngine.execute_prerequest(
            script_lines=script_lines, 
            env_vars=current_env, 
            request_body=req_body
        )
    
    # 4. Now 'current_env' has the new headers generated by the JS!
    return current_env